name: Test
on:
  pull_request:
    branches: [master]

env:
  APP_KEY: ${{ secrets.APP_KEY }}
  OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Install dependencies
      run: |
        composer install --prefer-dist
    - name: Set environment variables
      run: |
        echo "APP_KEY=$APP_KEY" >> $GITHUB_ENV
        echo "OPEN_AI_API_KEY=$OPEN_AI_API_KEY" >> $GITHUB_ENV
    - name: Build assets
      run: |
        npm install
        npm run build
    - name: Run tests
      run: |
        ./vendor/bin/phpunit --testdox tests/
