name: Test
on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up PHP
      uses: actions/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install dependencies
      run: composer install --prefer-dist

    - name: Run tests and linter
      run: |
        php artisan test
        ./vendor/bin/parallel-lint app/ database/ tests/
