name: Test
on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2.2.0
      with:
        php-version: '8.0'

    - name: Install dependencies
      run: composer install --prefer-dist

    - name: Run tests and linter
      run: |
        php artisan test
        ./vendor/bin/parallel-lint app/ database/ tests/
